config/routes.rb
Rails.application.routes.draw do
  resources :articledetails
  resources :items
  resources :articles
  resources :promotions
  resources :contacts
  resources :abouts
  resources :products
  resources :dealers
  root to: 'products#index'

  devise_for :users, controllers: { registrations: 'users/registrations' }
  
  get '/innovations', to: "products#innovations"
  get '/weeklyadds', to: "dealers#weeklyadds"
  get '/blackfriday', to: "dealers#blackfriday"
  get '/dailydeals', to: "dealers#dailydeals"
  get '/finders', to: "dealers#finders"
  get '/associates', to: "dealers#associates"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


end

app/models/article.rb
class Article < ApplicationRecord
	has_many :items
	has_many :articledetails
	has_one_attached :photo
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  load_and_authorize_resource
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy

    @items = Item.where(article_id: @article.id)

    @items.each do |item|
      item.destroy
    end

    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :heading, :conclusion, :writer, :famousquote, :famousquoteby, :photo)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= simple_form_for(@article) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

<div class="newform-box">
  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :heading %>
    <%= f.input :conclusion %>
    <%= f.input :writer %>
    <%= f.input :famousquote %>
    <%= f.input :famousquoteby %>
    <%= f.input :photo %>
  </div>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
</div><!--end newform-box input-->
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1></br>

<div class = "container">
	<%= render 'form', article: @article %>
	<%= link_to 'Show', @article %> |
	<%= link_to 'Back', articles_path %>
</div>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<%- model_class = Article -%>
<div class="container ">
  <!--<div class="page-header"><h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1></div>-->

  <div class="row mb-2 justify-content-center">
    <% @articles.each do |article| %>
      <div class="card border-0 bg-light mb-3 mr-5" style="max-width: 15rem; max-height: 30rem;">
        <picture><%= image_tag(article.photo, class: "card-img-top rounded") %></picture>
        <div class="card-body"> 
          <h5 class="card-title text-center font-weight-bold"><%= link_to article.title, article %></h5>
          <div class="dropdown-divider"></div>
          <h6 class="text-left font-weight-bold"><%= article.writer %></h6></br>
          <h6 class="text-right"><%= article.created_at.strftime("%b, %Y") %></h6>
        </div>
        <div class="card-footer">
          <a class="text-center font-weight-bold">
          <%=  link_to( 'Read More ..', article,:target => :blank, :class => 'btn btn-warning btn-sm')%> <span class="badge badge-light text-right"><%= article.items.count %></span>
          </a>
          <div>
            <% if can? :update, article %>
              <%= article.id %>||
              <%= link_to 'New Article', new_article_path %>||
              <%= link_to 'New Item', new_item_path %>||
              <%= link_to 'New Articledetail', new_articledetail_path %>||
              <%= link_to 'Show', article %> ||
              <%= link_to 'Edit', edit_article_path(article) %> ||
              <%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %>
            <%end%>
          </div>
        </div>
      </div>
    <% end %>
  </div><!--finished row-->
</div><!--finished container-->

app/views/articles/new.html.erb
<h1>New Article</h1></br>

<div class="container">
  <div class="row">
	<%= render 'form', article: @article %>
  </div>
  <div class="row">
	<%= link_to 'Back', articles_path %>
  </div>
</div>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <div class="row justify-content-center">
    <div class = "col-md-12">
      <div class="card rounded ml-2 mb-3">
          <picture><%= image_tag(@article.photo, class: "card-img-top rounded") %></picture>
          <div class="card-img-overlay">
            <div class="container position-absolute mid-left">
              <P class="h3 font-weight-bold text-white mb-2"><%= @article.title %></p>
              <p class="h6 font-italic text-white"><%= @article.writer %>
              <%= @article.created_at.strftime("%b, %Y") %></p>
            </div>
          </div>
      </div>
    </div>
  </div>
  
  <div class="row justify-content-center">
    <div class = "col-md-9">
      <div class="container mt-2 ml-2 mb-2">
        <div class="text-justify mb-2"><%= @article.heading %></div>
      </div>
 
      <div class="articledetail-box">
        <div class="container p-2">
          <p class="h5 font-weight-bold"><u>Highlights:</u></p>
            <% @article.articledetails.each do |articledetail| %>
              <ul>
                <li class="h5 font-weight-bold text-monospace ml-2 mb-2"><%= articledetail.title %></li>
              </ul>
            <% end %>
        </div>
      </div>

      <div class="container rounded mt-3 ml-2 mb-3">
        <% @article.articledetails.each do |articledetail| %>
        <div class="row no-gutters">
          <div class="container ml-2 mb-2">
            <p class="h5 font-weight-bold mb-2">* <%= articledetail.title %></p>
            <div class="card-text text-justify"><%= articledetail.content %></div>
          </div>     
        </div>
        <% end %>
      </div> <!--end <div class="container rounded ml-2 mb-3"> -->

      <div class="articlequote-box">
        <div class="container p-2">
          <p class="h6 font-italic"><%= @article.famousquote %> </p>
          <p class="font-italic">-<%= @article.famousquoteby %> </p>
        </div>
      </div>
 
      <% @article.items.each do |item| %>
        <div class="card rounded ml-2 mt-2 mb-3">
  	      <div class="row no-gutters">
  		      <div class="col-md-5">
              <picture><%= image_tag(item.image, class: 'fit-picture') %></picture>
  		      </div>
  		      <div class="col-md-7">
  			      <div class="container">
                <div class="row justify-content-center">
                  <p class ="h4 font-weight-bold text-center"><%= item.itemname %></p></br>
                </div>
                <div class="row justify-content-center">
                  <p class="h6 font-italic"><%= item.created_at.strftime("%b, %Y") %></p>
                </div>
                <div class="dropdown-divider"></div>
                <div  class="row justify-content-left ml-2">
                  <div class="text-justify"><%= item.itemdescription %></div>
                </div>
                <div class="dropdown-divider"></div>
                <div  class="row justify-content-between">
                  <div class="col">
                  <%=  link_to( 'Product Link' , url_with_protocol(item.itemurl),:target => :blank, :class => 'btn btn-danger btn-md')%>
                  </div>
                  <div class="col text-align-right">
                  <font size="4" color = #0000FF><%= number_to_currency(item.itemprice, :unit => "@$")%></font></p></div>
                </div>
              </div>
  			    </div>	
			    </div>
		    </div>
	    <% end %>
      <div class="articledetail-conclusion">
        <div class="container">
          <p class="h5 font-weight-bold text-monospace mt-2 ml-2 mb-2"><u>Key Takeaways:</u></p>
          <div class="text-justify mb-2"><%= @article.conclusion %></div>
          <div class="dropdown-divider"></div>
   	    <div>
   		  <% if can? :update, @article %>
     	    <%= link_to 'Edit', edit_article_path(@article) %>
     	    <%= link_to 'Destroy', @article, method: :delete, data: { confirm: 'Are you sure?' } %>
          <%= link_to 'New About', new_article_path %>
        <%end%>
        <div><%= link_to 'Back', articles_path %></div>
      </div>
    </div><!----end container-->
  </div><!----article-conclusion-->
</div><!--col-md-10-->