config/routes.rb
Rails.application.routes.draw do
  resources :articledetails
  resources :items
  resources :articles
  resources :promotions
  resources :contacts
  resources :abouts
  resources :products
  resources :dealers
  root to: 'products#index'

  devise_for :users, controllers: { registrations: 'users/registrations' }
  
  get '/innovations', to: "products#innovations"
  get '/weeklyadds', to: "dealers#weeklyadds"
  get '/blackfriday', to: "dealers#blackfriday"
  get '/dailydeals', to: "dealers#dailydeals"
  get '/finders', to: "dealers#finders"
  get '/associates', to: "dealers#associates"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
       user ||= User.new # guest user (not logged in)
       if user.admin?
         can :manage, :all
       else
         can :read, :all
       end
    end
end

app/models/about.rb
class About < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	has_many :items
	has_many :articledetails
	has_one_attached :photo
end

app/models/articledetail.rb
class Articledetail < ApplicationRecord
	belongs_to :article
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/dealer.rb
class Dealer < ApplicationRecord
	has_one_attached :logo
end

app/models/item.rb
class Item < ApplicationRecord
	belongs_to :article
	has_one_attached :image
end

app/models/product.rb
class Product < ApplicationRecord
	has_one_attached :picture
	has_one_attached :animation
end

app/models/promotion.rb
class Promotion < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/dealers_helper.rb
module DealersHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/promotions_helper.rb
module PromotionsHelper
end

app/helpers/urls_helper.rb
module UrlsHelper   

   def url_with_protocol(url)     
		/^http/.match(url) ? url : "http://#{url}"   
   end 
	
   def button(*args)
    if args.size == 2
      name = args[0]
      url = args[1]
      content_tag :button, :type => "button", :onclick => "window.location.href =  '#{url_for(url)}'; "  do
        "#{name}"
      end
    elsif args.size == 1
      name = args[0]
      content_tag :button, :type => "button"  do
        "#{name}"
      end
    end
  end
	
end

app/views/layouts/_alerts.html.erb
<!--Amol added following two lines from device gem install. Rethink 3/26 10 pm.-->
       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <title>WowMe!</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge, chrome=1">
    <%= favicon_link_tag 'wowmewiththathd.png'%>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"><!--Amol added this line. -->
    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= render 'shared/google'%>
    <script src='https://www.google.com/recaptcha/api.js'></script>

    

  </head>


<div class="container-fluid">
  <body>
    <div class="row"><%= render 'shared/navbar'%></div>
    <div class="row mb 2">
      <%= render 'shared/temp1'%> 
      <%= render 'shared/alerts'%>
    </div>
    <div class="row mb 2">
      <%= yield %>
    </div>
    <div class="row"><%= render 'shared/footer'%></div>
  </body>
</div>
</html>

app/views/layouts/standard.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= favicon_link_tag 'iconhd.png'%>
  <title>DeAlibaba!!</title>
   [if lt IE 11]>
  	<script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  [endif]
  	
  	
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name ="viewport" content="width=device-width, initial - scale=1.0">
</head>

<body>
	<div class="container fluid">
		<div class="row">
			<!--<%= render 'shared/navbar'%>-->
	  		<%= render 'shared/alerts'%>
	  	</div>
	</div>

		<div class="container">
		  <div class="row">
		     <div class="span10 offset1"> <%= yield %> </div>
		  </div>
	  </div>

	<div class="container">
		<div class="row"><%= render 'shared/footer'%>	</div>
	</div>
</body>
</html>

app/views/shared/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/shared/_footer.html.erb
 <div class="container-fluid">
<nav class="navbar text-center navbar-expand-lg sticky-bottom" style="background-color: #e3f2fd;">
  <!--<a class="navbar-brand" href="#">DEalibaba.com</a>-->
  <div>
    <% logo = image_tag("wowmewiththatlogo1.png", :alt => "wowmewiththat.com") %>
    <%= link_to logo, root_path %>
  </div>
  
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="nav nav-pills font-color: #F6FF33" >
      <li class="nav-item active">
          <li class="nav-item"><%= link_to 'Innovations', root_path, class: 'navbar-brand' %></li>
          <li class="nav-item"><%= link_to 'Vendors', dealers_path, class: 'navbar-brand'%></li>
          <li class="nav-item"><%= link_to 'About', abouts_path, class: 'navbar-brand' %></li>
          <li class="nav-item"><%= link_to 'Contact', contacts_path, class: 'navbar-brand' %></li>
        </li>
      </li>
      <div class = "span8 text-right">
	     <%= image_tag("facebook.png", :size => "40x40", :alt => "dealibaba.com")%>
	     <%= image_tag("twitter.png",  :size => "40x40", :alt => "dealibaba.com")%>
	     <%= image_tag("google.png",   :size => "40x40", :alt => "dealibaba.com")%>
	     <%= image_tag("pinterest.png",:size => "40x40", :alt => "dealibaba.com")%>
	     <%= image_tag("mail.png",     :size => "40x40", :alt => "dealibaba.com")%>
	    </div>
    </ul>
  </div>
</nav>
</div>

app/views/shared/_google.html.erb
<% if Rails.env.production? %>
	<!-- Global site tag (gtag.js) - Google Analytics -->
	<script async src="https://www.googletagmanager.com/gtag/js?id=UA-140151298-1"></script>
	<script>
  		window.dataLayer = window.dataLayer || [];
  		function gtag(){dataLayer.push(arguments);}
  		gtag('js', new Date());

  		gtag('config', 'UA-140151298-1');
	</script>
<% end %>

app/views/shared/_navbar.html.erb
<div class="container-fluid">
  <nav class="navbar fixed-top navbar-expand-lg navbar-light">
    <div>
      <% logo = image_tag("wowmewiththatlogo1.png", :alt => "wowmewiththat.com") %>
      <%= link_to logo, root_path %>
    </div>
  
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="nav nav-pills ">
        <li class="nav-item active">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Innovations</a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a><%=  link_to 'Innovations', products_path %></a>
              <div class="dropdown-divider"></div>
              <a><%=  link_to( "Kids",products_path(productcategory: 'Kids')) %> </a>
              <div class="dropdown-divider"></div>
              <a><%=  link_to( "Hers" ,products_path(productcategory: 'Hers')) %></a>
              <div class="dropdown-divider"></div>
              <a><%=  link_to( "His" ,products_path(productcategory: 'His')) %></a>
              <div class="dropdown-divider"></div>
              <a><%=  link_to( "Gadgets" ,products_path(productcategory: 'Gadgets'))%></a>
              <div class="dropdown-divider"></div>
              <a><%=  link_to( "Pets" ,products_path(productcategory: 'Pets'))%></a>
            </div>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Browse Deals</a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a><%=  link_to 'Weekly Adds', weeklyadds_path %></a>
              <div class="dropdown-divider"></div>
              <a><%=  link_to 'Associates', associates_path %></a>
              <div class="dropdown-divider"></div>
              <a><%=  link_to 'Deal Finders', finders_path %></a>
              <div class="dropdown-divider"></div>
              <a><%=  link_to 'Daily Deals', dailydeals_path %></a>
              <div class="dropdown-divider"></div>
              <a><%=  link_to 'Black Friday', blackfriday_path %></a>
              <div class="dropdown-divider"></div>
              <a><%=  link_to 'See All', dealers_path %></a>
            </div>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Blog</a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a><%=  link_to 'Articles', articles_path %></a>
              <div class="dropdown-divider"></div>
              <a><%=  link_to 'See All', articles_path %></a>
            </div>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Links</a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a><%=  link_to 'About', abouts_path %></a>
              <div class="dropdown-divider"></div>
              <a><%=  link_to 'Contact', contacts_path %></a>
            </div>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Account</a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <% if user_signed_in? %>
                <a class="dropdown-item" href="#"><%= link_to('My Account', edit_user_registration_path) %></a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#"><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></a>
                <div class="dropdown-divider"></div>
              <% else %>
                <a class="dropdown-item" href="#"><%= link_to("Sign in", new_user_session_path) %></a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#"><%= link_to("Sign up", new_user_registration_path) %></a>
              <% end %>
            </div>
          </li>
        </li>
      </ul>
    </div>
  </nav>
</div>

app/views/shared/_navbardark.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="#">Brand</a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">
      <li class="active"><a href="#">Link</a></li>
      <li><a href="#">Link</a></li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><a href="#">Action</a></li>
          <li><a href="#">Another action</a></li>
          <li><a href="#">Something else here</a></li>
          <li class="divider"></li>
          <li><a href="#">Separated link</a></li>
          <li class="divider"></li>
          <li><a href="#">One more separated link</a></li>
        </ul>
      </li>
    </ul>
    <form class="navbar-form navbar-left" role="search">
      <div class="form-group">
        <input type="text" class="form-control" placeholder="Search">
      </div>
      <button type="submit" class="btn btn-default">Submit</button>
    </form>
    <ul class="nav navbar-nav navbar-right">
      <li><a href="#">Link</a></li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><a href="#">Action</a></li>
          <li><a href="#">Another action</a></li>
          <li><a href="#">Something else here</a></li>
          <li class="divider"></li>
          <li><a href="#">Separated link</a></li>
        </ul>
      </li>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>
<div class="container-fluid">
  <div class="jumbotron mb-2 text-center">
    <a><%=  link_to( "See All",products_path, :class => 'btn btn-secondary btn-lg')%></a>


    <a><%=  link_to( "Kids" ,products_path(productcategory: 'Kids'), :class => 'btn btn-secondary btn-lg')%></a>


    <a><%=  link_to( "Hers" ,products_path(productcategory: 'Hers'), :class => 'btn btn-secondary btn-lg')%></a>

    <a><%=  link_to( "His" ,products_path(productcategory: 'His'), :class => 'btn btn-secondary btn-lg')%></a>

    <a><%=  link_to( "Gadget" ,products_path(productcategory: 'Gadgets'), :class => 'btn btn-secondary btn-lg')%></a>

    <a><%=  link_to( "Gadget" ,products_path(productcategory: 'Gadgets'), :class => 'btn btn-secondary btn-lg')%></a>

  </div>
</div>

app/views/shared/_temp.html.erb
<div class="container">
 <nav class="navbar fixed-top">
  

<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
</button>



<ul class="nav nav-tabs">
  <li class="nav-item">
    <a><%=  link_to 'See All', products_path %></a>
  </li>
  <li class="nav-item">
    <a><%=  link_to 'Kids', products_path(productcategory: 'Kids') %></a>
  </li>
  <li class="nav-item">
    <a><%=  link_to 'Hers', products_path(productcategory: 'Hers') %></a>
  </li>
  <li class="nav-item">
    <a><%=  link_to 'His',  products_path(productcategory: 'His') %></a>
  </li>
  <li class="nav-item">
    <a><%=  link_to 'Pets', products_path(productcategory: 'Pets') %></a>
  </li>
 </nav>
</div>

app/views/shared/_temp1.html.erb
<div class="container-fluid">

 <nav class="navbar second-navbar navbar-expand-lg navbar-light text-center" style="background-color: #D0FBE7;">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
  </button>
  
  <div class="collapse navbar-collapse" id="navbarNavDropdown">

 
    <a><%=  link_to( "Weekly Adds",weeklyadds_path, :class => 'btn btn-outline-info btn-block')%></a>

    <a><%=  link_to( "Associates",associates_path, :class => 'btn btn-outline-info btn-block')%></a>

    <a><%=  link_to( "All Innovations",products_path, :class => 'btn btn-outline-info btn-block')%></a>

    <a><%=  link_to( "Kids" ,products_path(productcategory: 'Kids'), :class => 'btn btn-outline-info btn-block')%></a>
  
    <a><%=  link_to( "Hers" ,products_path(productcategory: 'Hers'), :class => 'btn btn-outline-info btn-block')%></a>

    <a><%=  link_to( "His" ,products_path(productcategory: 'His'), :class => 'btn btn-outline-info btn-block')%></a>
 
    <a><%=  link_to( "Gadgets" ,products_path(productcategory: 'Gadgets'), :class => 'btn btn-outline-info btn-block')%></a>
	</div>
  </nav>
</div>