config/routes.rb
Rails.application.routes.draw do
  resources :articledetails
  resources :items
  resources :articles
  resources :promotions
  resources :contacts
  resources :abouts
  resources :products
  resources :dealers
  root to: 'products#index'

  devise_for :users, controllers: { registrations: 'users/registrations' }
  
  get '/innovations', to: "products#innovations"
  get '/weeklyadds', to: "dealers#weeklyadds"
  get '/blackfriday', to: "dealers#blackfriday"
  get '/dailydeals', to: "dealers#dailydeals"
  get '/finders', to: "dealers#finders"
  get '/associates', to: "dealers#associates"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
       user ||= User.new # guest user (not logged in)
       if user.admin?
         can :manage, :all
       else
         can :read, :all
       end
    end
end

app/models/about.rb
class About < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	has_many :items
	has_many :articledetails
	has_one_attached :photo
end

app/models/articledetail.rb
class Articledetail < ApplicationRecord
	belongs_to :article
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/dealer.rb
class Dealer < ApplicationRecord
	has_one_attached :logo
end

app/models/item.rb
class Item < ApplicationRecord
	belongs_to :article
	has_one_attached :image
end

app/models/product.rb
class Product < ApplicationRecord
	has_one_attached :picture
	has_one_attached :animation
end

app/models/promotion.rb
class Promotion < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/articledetails_controller.rb
class ArticledetailsController < ApplicationController
  load_and_authorize_resource
  before_action :set_articledetail, only: [:show, :edit, :update, :destroy]

  # GET /articledetails
  # GET /articledetails.json
  def index
    @articledetails = Articledetail.all
  end

  # GET /articledetails/1
  # GET /articledetails/1.json
  def show
  end

  # GET /articledetails/new
  def new
    @articledetail = Articledetail.new
  end

  # GET /articledetails/1/edit
  def edit
  end

  # POST /articledetails
  # POST /articledetails.json
  def create
    @articledetail = Articledetail.new(articledetail_params)

    respond_to do |format|
      if @articledetail.save
        format.html { redirect_to @articledetail, notice: 'Articledetail was successfully created.' }
        format.json { render :show, status: :created, location: @articledetail }
      else
        format.html { render :new }
        format.json { render json: @articledetail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articledetails/1
  # PATCH/PUT /articledetails/1.json
  def update
    respond_to do |format|
      if @articledetail.update(articledetail_params)
        format.html { redirect_to @articledetail, notice: 'Articledetail was successfully updated.' }
        format.json { render :show, status: :ok, location: @articledetail }
      else
        format.html { render :edit }
        format.json { render json: @articledetail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articledetails/1
  # DELETE /articledetails/1.json
  def destroy
    @articledetail.destroy
    respond_to do |format|
      format.html { redirect_to articledetails_url, notice: 'Articledetail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_articledetail
      @articledetail = Articledetail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def articledetail_params
      params.require(:articledetail).permit(:title, :content, :article_id, :heading, :link, :quote)
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  load_and_authorize_resource
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:itemname, :itemurl, :itemprice, :itembutton, :itemdescription, :article_id, :image)
    end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articledetails_helper.rb
module ArticledetailsHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/dealers_helper.rb
module DealersHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/promotions_helper.rb
module PromotionsHelper
end

app/helpers/urls_helper.rb
module UrlsHelper   

   def url_with_protocol(url)     
		/^http/.match(url) ? url : "http://#{url}"   
   end 
	
   def button(*args)
    if args.size == 2
      name = args[0]
      url = args[1]
      content_tag :button, :type => "button", :onclick => "window.location.href =  '#{url_for(url)}'; "  do
        "#{name}"
      end
    elsif args.size == 1
      name = args[0]
      content_tag :button, :type => "button"  do
        "#{name}"
      end
    end
  end
	
end

app/views/articledetails/_form.html.erb
<%= simple_form_for(@articledetail) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>


<div class="newform-box">
  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :content %>
    <%= f.input :article_id %>
    <%= f.input :heading %>
    <%= f.input :link %>
    <%= f.input :quote %>
  </div>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
 </div><!--end newform-box input-->
<% end %>

app/views/articledetails/edit.html.erb
<h1>Editing Articledetail</h1></br>


<div class = "container">
	<%= render 'form', articledetail: @articledetail %>
	<%= link_to 'Show', @articledetail %> |
	<%= link_to 'Back', articledetails_path %>
</div>

app/views/articledetails/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Articledetails</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Article</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articledetails.each do |articledetail| %>
      <tr>
        <td><%= articledetail.title %></td>
        <td><%= articledetail.content %></td>
        <td><%= articledetail.article_id %></td>
        <td><%= articledetail.heading %></td>
        <td><%= articledetail.link %></td>
        <td><%= articledetail.quote %></td>
        <td><%= link_to 'Show', articledetail %></td>
        <td><%= link_to 'Edit', edit_articledetail_path(articledetail) %></td>
        <td><%= link_to 'Destroy', articledetail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Articledetail', new_articledetail_path %>

app/views/articledetails/new.html.erb
<h1>New Articledetail</h1></br>

<div class="container">
  <div class="row">
	<%= render 'form', articledetail: @articledetail %>
  </div>
  <div class="row">
	<%= link_to 'Back', articledetails_path %>
  </div>
</div>

app/views/articledetails/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @articledetail.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @articledetail.content %>
</p>

<p>
  <strong>Article:</strong>
  <%= @articledetail.article_id %>
</p>

<%= link_to 'Edit', edit_articledetail_path(@articledetail) %> |
<%= link_to 'Back', articledetails_path %>