config/routes.rb
Rails.application.routes.draw do
  resources :articledetails
  resources :items
  resources :articles
  resources :promotions
  resources :contacts
  resources :abouts
  resources :products
  resources :dealers
  root to: 'products#index'

  devise_for :users, controllers: { registrations: 'users/registrations' }
  
  get '/innovations', to: "products#innovations"
  get '/weeklyadds', to: "dealers#weeklyadds"
  get '/blackfriday', to: "dealers#blackfriday"
  get '/dailydeals', to: "dealers#dailydeals"
  get '/finders', to: "dealers#finders"
  get '/associates', to: "dealers#associates"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
       user ||= User.new # guest user (not logged in)
       if user.admin?
         can :manage, :all
       else
         can :read, :all
       end
    end
end

app/models/about.rb
class About < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	has_many :items
	has_many :articledetails
	has_one_attached :photo
end

app/models/articledetail.rb
class Articledetail < ApplicationRecord
	belongs_to :article
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/dealer.rb
class Dealer < ApplicationRecord
	has_one_attached :logo
end

app/models/item.rb
class Item < ApplicationRecord
	belongs_to :article
	has_one_attached :image
end

app/models/product.rb
class Product < ApplicationRecord
	has_one_attached :picture
	has_one_attached :animation
end

app/models/promotion.rb
class Promotion < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController
  load_and_authorize_resource
  before_action :set_about, only: [:show, :edit, :update, :destroy]

  # GET /abouts
  # GET /abouts.json
  def index
    @abouts = About.all
  end

  # GET /abouts/1
  # GET /abouts/1.json
  def show
  end

  # GET /abouts/new
  def new
    @about = About.new
  end

  # GET /abouts/1/edit
  def edit
  end

  # POST /abouts
  # POST /abouts.json
  def create
    @about = About.new(about_params)

    respond_to do |format|
      if @about.save
        format.html { redirect_to @about, notice: 'About was successfully created.' }
        format.json { render :show, status: :created, location: @about }
      else
        format.html { render :new }
        format.json { render json: @about.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /abouts/1
  # PATCH/PUT /abouts/1.json
  def update
    respond_to do |format|
      if @about.update(about_params)
        format.html { redirect_to @about, notice: 'About was successfully updated.' }
        format.json { render :show, status: :ok, location: @about }
      else
        format.html { render :edit }
        format.json { render json: @about.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /abouts/1
  # DELETE /abouts/1.json
  def destroy
    @about.destroy
    respond_to do |format|
      format.html { redirect_to abouts_url, notice: 'About was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_about
      @about = About.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def about_params
      params.require(:about).permit(:question, :answer)
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  load_and_authorize_resource
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:itemname, :itemurl, :itemprice, :itembutton, :itemdescription, :article_id, :image)
    end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articledetails_helper.rb
module ArticledetailsHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/dealers_helper.rb
module DealersHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/promotions_helper.rb
module PromotionsHelper
end

app/helpers/urls_helper.rb
module UrlsHelper   

   def url_with_protocol(url)     
		/^http/.match(url) ? url : "http://#{url}"   
   end 
	
   def button(*args)
    if args.size == 2
      name = args[0]
      url = args[1]
      content_tag :button, :type => "button", :onclick => "window.location.href =  '#{url_for(url)}'; "  do
        "#{name}"
      end
    elsif args.size == 1
      name = args[0]
      content_tag :button, :type => "button"  do
        "#{name}"
      end
    end
  end
	
end

app/views/abouts/_form.html.erb
<%= simple_form_for(@about) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
 

<div class="newform-box">
  <div class="form-inputs">
    <%= f.input :question %>
    <%= f.input :answer %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
</div><!--end newform-box input-->



<% end %>

app/views/abouts/edit.html.erb
<h1>Editing About</h1>

<div class = "container">
	<%= render 'form', about: @about %>
	<%= link_to 'Show', @about %> |
	<%= link_to 'Back', abouts_path %>
</div>

app/views/abouts/index.html.erb
<%- model_class = About -%>
<div class="container">
  <div class="row">
    <div class="page-header">
      <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
    </div>
  </div><!--end row-->

  <div class="row">
    <% @abouts.each do |about| %>
        <div class="card border-0 rounded bg-light mb-2 mr-2" style="max-width: 35rem; height: auto;">
          <h4 class="card-header font-weight-bold"><%= about.question %></h4>
          <div class="card-body"> 
            <div class="card-text"><%= about.answer %></div>
          </div>

          <div class ="card-footer">
            <% if can? :update, about %>
              <%= link_to 'Show', about %>
              <%= link_to 'Edit', edit_about_path(about) %>
              <%= link_to 'Destroy', about, method: :delete, data: { confirm: 'Are you sure?' } %>
              <%= link_to 'New About', new_about_path %>
            <%end%>
          </div>
        </div><!--end card-->
    <% end %>
  </div><!--end row-->
</div><!--end container-->

app/views/abouts/new.html.erb
<h1>New About</h1></br>

<div class="container">
  <div class="row">
	<%= render 'form', about: @about %>
  </div>
  <div class="row">
	<%= link_to 'Back', abouts_path %>
  </div>
</div>

app/views/abouts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Question:</strong>
  <%= @about.question %>
</p>

<p>
  <strong>Answer:</strong>
  <%= @about.answer %>
</p>

<% if can? :update, @about %>
<%= link_to 'Edit', edit_about_path(@about) %> |
<% end %>
<%= link_to 'Back', abouts_path %>

app/views/items/_form.html.erb
<%= simple_form_for(@item) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

<div class="newform-box">
  <div class="form-inputs">
    <%= f.input :itemname %>
    <%= f.input :itemurl %>
    <%= f.input :itemprice %>
    <%= f.input :itembutton %>
    <%= f.input :itemdescription %>
    <%= f.input :article_id %>
    <%= f.input :image %>
  </div>
</div><!--end newform-box input-->

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<%- model_class = Item -%>

<div class="container">
  <!--<div class="page-header"><h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1></div>-->

  <div class="row mb-2">
    <% @items.each do |item| %>
      <div class="col-md-3">
        <div class="card border-primary bg-light mb-3" style="max-width: 18rem;">
          <div class="card-header">
            <%= link_to(item.itemname, url_with_protocol(item.itemurl),:target => :blank) %>
          </div>
          <div class="card-body">
            <picture><%= image_tag(item.image, class: 'fit-picture') %></picture>
            <div class="dropdown-divider"></div>
            <p class="card-text"><%= item.itemdescription %> </p>
          <div class="card-footer">
            <p><a class="card-text"><%=  link_to( item.itembutton , url_with_protocol(item.itemurl),:target => :blank, :class => 'btn btn-warning btn-sm')%></a>
            <a class="float-right"><font size="4" color = #0000FF><%= number_to_currency(item.itemprice, :unit => "@$")%></font></a>
            </p>
            <div>
              <% if can? :update, item %>
                <%= item.id %>
                <%= link_to 'Show', item %> ||
                <%= link_to 'Edit', edit_item_path(item) %> ||
                <%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %>||
                <%= link_to 'New product', new_item_path %>
              <%end%>
            </div>
          </div>
        </div>
      </div>
    </div>
    <% end %>
</div><!--finished container-->


<%= link_to 'New Article', new_article_path %>
<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New Item</h1></br>

<div class="container">
  <div class="row">
	<%= render 'form', item: @item %>
  </div>
  <div class="row">
	<%= link_to 'Back', items_path %>
  </div>
</div>
 

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Itemname:</strong>
  <%= @item.itemname %>
</p>

<p>
  <strong>Itemurl:</strong>
  <%= @item.itemurl %>
</p>

<p>
  <strong>Itemprice:</strong>
  <%= @item.itemprice %>
</p>

<p>
  <strong>Itembutton:</strong>
  <%= @item.itembutton %>
</p>

<p>
  <strong>Itemdescription:</strong>
  <%= @item.itemdescription %>
</p>

<p>
  <strong>Article:</strong>
  <%= @item.article_id %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>